# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://erwangranger.github.io/nbdevtest01/"

git_url = "https://github.com/erwangranger/nbdevtest01/tree/main/"

def custom_doc_links(name): return None
